---
# tasks file for static_web_app/config

- name: npm install package
  shell: npm isntall
  args:
    chdir: "{{npm_app_dest_directory}}"
  become: yes

- name: npm build app
  shell: npm run build
  args:
    chdir: "{{npm_app_dest_directory}}"
  become: yes