---
# tasks file for static_web_app/config

- name: npm install package
  shell: npm isntall
  args:
    chdir: "{{npm_app_dest_directory}}"
  become: yes

# - name: npm fix package
#   shell: npm audit fix
#   args:
#     chdir: "{{npm_app_dest_directory}}"
#   become: yes

- name: npm install serve
  npm: 
    name: serve
    global: yes
  become: yes

- name: npm install pm2
  npm: 
    name: pm2
    global: yes
  become: yes

