---
# tasks file for tiquet-frontend/install

- name: Install npm
  apt:
    name: npm
    update_cache: yes
    force_apt_get: yes
    force: yes
  become: yes

# - name: update apt
#   apt:
#     name: "*"
#     state: latest