---
# tasks file for tiquet-backend/install

- name: Install npm
  apt:
    name: npm
    update_cache: yes
    force_apt_get: yes
    force: yes
  become: yes

- name: Add repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    force_apt_get: yes
    force: yes
  become: yes

- name: Install python
  apt:
    name: 
      - python3.8
      - python3-pip
      - python3-virtualenv
    update_cache: yes
    force_apt_get: yes
    force: yes
  become: yes

- name: npm install serve
  npm: 
    name: serve
    global: yes
  become: yes

- name: npm install pm2
  npm: 
    name: pm2
    global: yes
  become: yes

- name: update apt
  apt:
    name: "*"
    state: latest
  become: yes