---
# tasks file for grafana

- name: "Install grafana"
  import_tasks: "install.yml"

- name: "Run grafana server"
  import_tasks: "run.yml"

- name: "Configure grafana server"
  import_tasks: "config.yml"