---
# tasks file for influxdb/download

- name: Install curl
  apt:
    name: curl
    update_cache: yes
    force_apt_get: yes
    force: yes
  become: yes

- name: Download packages
  shell: curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  become: yes

- name: Download packages
  shell: echo "deb https://repos.influxdata.com/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  become: yes