---
# appo webpage playbook

# Ubuntu - Grafana Single instance
- name: Grafana Single instance
  hosts: Instance1
  roles:
    - influxdb
    - grafana
  tags: 
    - GrafanaSingle
  vars:
    instance_host: vagrant
    infuxdb_ip: localhost

# Ubuntu - Grafana Single instance
- name: Grafana Multi instance
  hosts: 
    Instance1
    Instance2
    Instance3
  roles:
    - influxdb
    - grafana
  tags: 
    - GrafanaMulti
  vars:
    instance_host: vagrant
    infuxdb_ip: localhost

# Ubuntu - Grafana Single instance
- name: Grafana Split instance
  hosts: 
    Instance1
  roles:
    - influxdb
  tags: 
    - GrafanaSplit
  vars:
    instance_host: vagrant

# Ubuntu - Grafana Single instance
- name: Grafana Split instance
  hosts: 
    Instance2
  roles:
    - grafana
  tags: 
    - GrafanaSplit
  vars:
    instance_host: vagrant
    infuxdb_ip: 192.168.56.21