---
# appo webpage playbook

# Ubuntu - Grafana Single instance
- name: Grafana Single instance
  hosts: Instance1
  roles:
    - influxdb
    - grafana
  tags: 
    - GrafanaSingle
  vars:
    instance_host: matys
    application_name: static web app
    git_web_address: https://github.com/
    appliaction_repository: Matys98/my-cv.git
    app_dest_directory: /home/"{{instance_host}}"

# Ubuntu - Grafana Two instance
- name: Grafana Two instance 1
  hosts: Instance2
  roles:
    - nodejs
  tags: 
    - GrafanaTwo

# Ubuntu - Grafana Two instance
- name: Grafana Two instance 2
  hosts: Instance2
  roles:
    - rubyonrails
  tags: 
    - GrafanaTwo