---
# static webpage playbook 

# Ubuntu - Static webapp
- name: Static webapp
  hosts: Instance1
  roles:
    - git
    - nodejs
    - static_web_app
  tags: 
    - StaticWebAppOneInstance
  vars:
    instance_host: vagrant
    application_name: static web app
    git_web_address: https://github.com/
    appliaction_repository: Matys98/my-cv.git
    app_dest_directory: /home/vagrant/app/
    npm_app_dest_directory: /home/vagrant/app/cv/

# Ubuntu - Static webapp ALL instances
- name: Static webapp
  hosts: 
    Instance1
    Instance2
    Instance3
  roles:
    - git
    - nodejs
    - static_web_app
  tags: 
    - StaticWebAppThreeInstance
  vars:
    instance_host: vagrant
    application_name: static web app
    git_web_address: https://github.com/
    appliaction_repository: Matys98/my-cv.git
    app_dest_directory: /home/vagrant/app/
    npm_app_dest_directory: /home/vagrant/app/cv/