---
# tiquet webpage playbook 

# Ubuntu - TIQUET Single instance
- name: TIQUET Single instance
  hosts: Instance1
  roles:
    - git
    - postgresql
    - tiquet-frontend
  tags: 
    - TiquetSingle
  vars:
    instance_host: vagrant
    application_name: Tiquet
    appliaction_repository: FLiotta/Tiquet.git
    app_dest_directory: /home/vagrant/app
    app_dest_directory: /home/vagrant/app/
    npm_app_dest_directory: /home/vagrant/app/client
    pip_app_dest_directory: /home/vagrant/app/server


# Ubuntu - TIQUET Single instance
# - name: TIQUET All instance
#   hosts: 
#     Instance1
#     Instance2
#     Instance3
#   roles:
#     - nodejs
#     - python
#     - postgresql
#     - tiquet-frontend
#     - tiquet-backend
#   tags: 
#     - TiquetMulti
#   vars:
#     instance_host: vagrant