---
# tasks file for roles/postgresql/install
- name: update apt
  apt:
    name: "*"
    state: latest
  become: yes

- name: install postgresql
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: true
  
- name: Install postgresql-client-common
  apt:
    name: postgresql-client-common
    force_apt_get: yes
  become: yes

- name: Install postgresql-client
  apt:
    name: postgresql-client
    force_apt_get: yes
  become: yes