---
# tasks file for roles/postgresql/install

- name: Download postgresql 
  shell: curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
  become: yes

- name: Add postgresql deb package
  shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
  become: yes

- name: Install postgresql
  apt:
    name: postgresql
    force_apt_get: yes
  become: yes
  
- name: Install postgresql-client-common
  apt:
    name: postgresql-client-common
    force_apt_get: yes
  become: yes

- name: Install postgresql-client
  apt:
    name: postgresql-client
    force_apt_get: yes
  become: yes