---
# tasks file for postgresql

- name: "Install postgresql"
  import_tasks: "install.yml"

- name: "Run postgresql"
  import_tasks: "run_postgres.yml"

# - name: update apt
#   apt:
#     name: "*"
#     state: latest
#   become: yes