---
# tasks file for roles/postgresql/run_postgresql

- name: config pg_hba file
  template:
    src: pg_hba.conf
    dest: /tmp/pg_hba.conf
  become: yes

- name: Add PG config to file
  shell: cat > /etc/postgresql/14/main/pg_hba.conf
  become: yes

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
  become: yes